/**
 * HTML Report Generator.
 *
 * Generates a self-contained, interactive HTML report from a list of issues.
 * All CSS and JS are embedded — no external dependencies needed.
 */

import type { Issue, Severity } from "../shared/types/Issue.js";
import { WCAG_BY_CHECK } from "../shared/wcag/criteria.js";

export interface FileMetadata {
  name: string;
  id: string;
  version?: string;
  lastModified?: string;
}

interface Stats {
  total: number;
  critical: number;
  serious: number;
  moderate: number;
  minor: number;
}

export class HtmlReporter {
  generate(file: FileMetadata, issues: Issue[], totalNodes: number, durationMs: number): string {
    const stats = this.computeStats(issues);
    const generatedAt = new Date().toLocaleString("en-US", {
      year: "numeric", month: "long", day: "numeric",
      hour: "2-digit", minute: "2-digit",
    });

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>A11y Audit — ${this.esc(file.name)}</title>
  <style>${CSS}</style>
</head>
<body>
  <header class="page-header">
    <div class="header-inner">
      <div class="header-title">
        <span class="header-logo">◆</span>
        <h1>Accessibility Audit Report</h1>
      </div>
      <div class="header-meta">
        <p class="file-name">${this.esc(file.name)}</p>
        <p class="meta-line">
          <span>${totalNodes.toLocaleString()} nodes scanned</span>
          <span>·</span>
          <span>${(durationMs / 1000).toFixed(1)}s</span>
          <span>·</span>
          <span>${generatedAt}</span>
        </p>
      </div>
    </div>
  </header>

  <main class="page-main">

    <section class="summary-section">
      <h2 class="section-title">Summary</h2>
      <div class="stat-grid">
        ${this.renderStat("critical", stats.critical, "Critical")}
        ${this.renderStat("serious", stats.serious, "Serious")}
        ${this.renderStat("moderate", stats.moderate, "Moderate")}
        ${this.renderStat("minor", stats.minor, "Minor")}
      </div>
      ${stats.total === 0
        ? `<div class="no-issues"><span class="no-issues-icon">✓</span><p>No accessibility issues found! Great work.</p></div>`
        : `<p class="total-label">${stats.total} issue${stats.total !== 1 ? "s" : ""} found across 6 checks</p>`
      }
    </section>

    ${stats.total > 0 ? `
    <section class="filter-section">
      <h2 class="section-title">Filter</h2>
      <div class="filter-bar">
        <button class="filter-btn active" data-severity="all" onclick="filterIssues(this)">All (${stats.total})</button>
        ${stats.critical > 0 ? `<button class="filter-btn" data-severity="critical" onclick="filterIssues(this)">Critical (${stats.critical})</button>` : ""}
        ${stats.serious > 0 ? `<button class="filter-btn" data-severity="serious" onclick="filterIssues(this)">Serious (${stats.serious})</button>` : ""}
        ${stats.moderate > 0 ? `<button class="filter-btn" data-severity="moderate" onclick="filterIssues(this)">Moderate (${stats.moderate})</button>` : ""}
        ${stats.minor > 0 ? `<button class="filter-btn" data-severity="minor" onclick="filterIssues(this)">Minor (${stats.minor})</button>` : ""}
      </div>
    </section>

    <section class="issues-section">
      <h2 class="section-title">Issues</h2>
      <div class="issue-list" id="issueList">
        ${issues.map((issue, idx) => this.renderIssueCard(issue, idx + 1)).join("\n")}
      </div>
    </section>
    ` : ""}

  </main>

  <footer class="page-footer">
    <p>Generated by <strong>a11y-figma-audit</strong> · Checks 01–06 of WCAG 2.1 AA ·
      <a href="https://www.w3.org/WAI/WCAG21/quickref/" target="_blank" rel="noopener">WCAG Reference</a>
    </p>
  </footer>

  <script>${JS}</script>
</body>
</html>`;
  }

  private renderStat(sev: Severity, count: number, label: string): string {
    return `
      <div class="stat-cell sev-${sev} ${count === 0 ? "empty" : ""}">
        <span class="stat-count">${count}</span>
        <span class="stat-label">${label}</span>
      </div>`;
  }

  private renderIssueCard(issue: Issue, idx: number): string {
    const wcag = WCAG_BY_CHECK[issue.checkId];
    const pathStr = issue.nodePath.join(" › ");
    const detailRows = this.renderDetails(issue);

    return `
    <div class="issue-card" data-severity="${issue.severity}" data-check="${issue.checkId}">
      <div class="issue-card-header" onclick="toggleCard(this)">
        <div class="issue-left">
          <span class="issue-num">${idx}</span>
          <span class="sev-badge sev-${issue.severity}">${issue.severity}</span>
          <span class="check-tag">${issue.checkId}</span>
        </div>
        <div class="issue-center">
          <p class="issue-message">${this.esc(issue.message)}</p>
          ${pathStr ? `<p class="issue-path">${this.esc(pathStr)}</p>` : ""}
        </div>
        <div class="issue-right">
          <span class="wcag-tag">WCAG ${wcag.number} ${wcag.level}</span>
          <span class="toggle-icon">›</span>
        </div>
      </div>

      <div class="issue-card-body" style="display:none">
        <div class="detail-grid">
          <div class="detail-block">
            <h4>WCAG Criterion</h4>
            <p>
              <a href="${wcag.url}" target="_blank" rel="noopener">
                ${wcag.number} ${wcag.title} (Level ${wcag.level})
              </a>
            </p>
          </div>

          <div class="detail-block">
            <h4>Location</h4>
            <p class="path-chain">${pathStr ? this.esc(pathStr) : "—"}</p>
          </div>

          ${detailRows ? `
          <div class="detail-block detail-block-wide">
            <h4>Details</h4>
            <table class="detail-table">${detailRows}</table>
          </div>` : ""}

          ${issue.fix ? `
          <div class="detail-block detail-block-wide">
            <h4>How to fix</h4>
            <p class="fix-suggestion">${this.esc(issue.fix.suggestion)}</p>
          </div>` : ""}
        </div>
      </div>
    </div>`;
  }

  private renderDetails(issue: Issue): string {
    const d = issue.details;
    const rows: string[] = [];

    const add = (label: string, value: unknown) => {
      if (value === null || value === undefined) return;
      rows.push(`<tr><td class="detail-key">${label}</td><td class="detail-val">${this.esc(String(value))}</td></tr>`);
    };

    switch (issue.checkId) {
      case "01-text-contrast":
        add("Text color", d.textColor);
        add("Background", d.backgroundColor);
        add("Contrast ratio", d.contrastRatio !== undefined ? `${Number(d.contrastRatio).toFixed(2)}:1` : undefined);
        add("Required ratio", d.requiredRatio !== undefined ? `${Number(d.requiredRatio).toFixed(1)}:1` : undefined);
        add("Font size", d.fontSize !== undefined ? `${d.fontSize}px` : undefined);
        add("Bold", d.isBold !== undefined ? (d.isBold ? "Yes" : "No") : undefined);
        break;
      case "02-ui-contrast":
        add("Element type", d.elementType);
        add("Element color", d.elementColor);
        add("Background", d.backgroundColor);
        add("Contrast ratio", d.contrastRatio !== undefined ? `${Number(d.contrastRatio).toFixed(2)}:1` : undefined);
        add("Required ratio", "3.0:1");
        add("Stroke weight", d.strokeWeight !== undefined ? `${d.strokeWeight}px` : undefined);
        break;
      case "03-tap-target":
        add("Size", d.width !== undefined && d.height !== undefined ? `${d.width}×${d.height}px` : undefined);
        add("Min dimension", d.minDimension !== undefined ? `${d.minDimension}px` : undefined);
        add("Spacing to neighbor", d.spacing !== undefined ? `${Number(d.spacing).toFixed(0)}px` : undefined);
        add("Required", "24px minimum");
        break;
      case "04-text-size":
        add("Font size", d.fontSize !== undefined ? `${d.fontSize}px` : undefined);
        add("Recommended minimum", d.recommendedMin !== undefined ? `${d.recommendedMin}px` : undefined);
        add("Hard floor", d.hardFloor !== undefined ? `${d.hardFloor}px` : undefined);
        add("Exception", d.exceptionApplies ? "Yes (legal/caption context)" : undefined);
        break;
      case "05-focus-defined":
        add("Existing variants", Array.isArray(d.existingVariants) ? (d.existingVariants as string[]).join(", ") : undefined);
        add("Suggested prop", d.suggestedProp);
        break;
      case "06-focus-visibility":
        add("Focus variant", d.focusVariant);
        add("Baseline variant", d.baselineVariant);
        add("Indicator thickness", d.thickness !== undefined ? `${d.thickness}px` : undefined);
        add("Indicator color", d.indicatorColor);
        add("Indicator contrast", d.indicatorContrast !== undefined ? `${Number(d.indicatorContrast).toFixed(2)}:1` : undefined);
        add("Background", d.backgroundColor);
        break;
    }

    return rows.join("\n");
  }

  private computeStats(issues: Issue[]): Stats {
    return {
      total: issues.length,
      critical: issues.filter((i) => i.severity === "critical").length,
      serious: issues.filter((i) => i.severity === "serious").length,
      moderate: issues.filter((i) => i.severity === "moderate").length,
      minor: issues.filter((i) => i.severity === "minor").length,
    };
  }

  private esc(s: string): string {
    return s
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }
}

// ─── Embedded CSS ────────────────────────────────────────────────────────────

const CSS = `
:root {
  --bg: #F5F1E8;
  --bg2: #FAF7EE;
  --white: #ffffff;
  --navy: #1E3A5F;
  --ink: #1a1a1a;
  --ink2: #444;
  --ink3: #888;
  --border: #e0ddd4;
  --cr: #DC2626;
  --se: #EA580C;
  --mo: #B45309;
  --mi: #1E3A5F;
  --radius: 4px;
  --mono: 'SF Mono', 'Fira Code', 'Cascadia Code', monospace;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  background: var(--bg);
  color: var(--ink);
  line-height: 1.5;
  font-size: 14px;
}
a { color: var(--navy); }
a:hover { text-decoration: underline; }

.page-header {
  background: var(--navy);
  color: white;
  padding: 24px 32px;
}
.header-inner { max-width: 900px; margin: 0 auto; display: flex; flex-direction: column; gap: 8px; }
.header-title { display: flex; align-items: center; gap: 12px; }
.header-logo { font-size: 20px; opacity: 0.6; }
h1 { font-size: 20px; font-weight: 700; letter-spacing: -0.3px; }
.file-name { font-size: 15px; font-weight: 500; opacity: 0.9; }
.meta-line { font-size: 12px; opacity: 0.6; display: flex; gap: 8px; }

.page-main { max-width: 900px; margin: 0 auto; padding: 32px; display: flex; flex-direction: column; gap: 32px; }

.section-title { font-size: 11px; font-weight: 600; letter-spacing: 0.8px; text-transform: uppercase; color: var(--ink3); margin-bottom: 12px; }

.stat-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; }
.stat-cell {
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  padding: 20px 12px; border-radius: var(--radius); color: white; gap: 4px;
}
.stat-cell.sev-critical { background: var(--cr); }
.stat-cell.sev-serious  { background: var(--se); }
.stat-cell.sev-moderate { background: var(--mo); }
.stat-cell.sev-minor    { background: var(--mi); }
.stat-cell.empty { opacity: 0.3; }
.stat-count { font-size: 32px; font-weight: 700; line-height: 1; }
.stat-label { font-size: 11px; font-weight: 500; text-transform: uppercase; letter-spacing: 0.5px; opacity: 0.85; }
.total-label { font-size: 12px; color: var(--ink3); margin-top: 8px; }
.no-issues { display: flex; align-items: center; gap: 12px; padding: 16px; background: #ecfdf5; border: 1px solid #bbf7d0; border-radius: var(--radius); color: #065f46; margin-top: 12px; }
.no-issues-icon { font-size: 20px; }

.filter-bar { display: flex; gap: 8px; flex-wrap: wrap; }
.filter-btn {
  background: var(--white); border: 1px solid var(--border); padding: 6px 14px;
  border-radius: 20px; font-size: 12px; cursor: pointer; color: var(--ink2);
  transition: all 0.15s;
}
.filter-btn:hover { border-color: var(--navy); color: var(--navy); }
.filter-btn.active { background: var(--navy); color: white; border-color: var(--navy); }

.issue-list { display: flex; flex-direction: column; gap: 8px; }

.issue-card {
  background: var(--white);
  border: 1px solid var(--border);
  border-left: 3px solid #ccc;
  border-radius: var(--radius);
  overflow: hidden;
}
.issue-card[data-severity=critical] { border-left-color: var(--cr); }
.issue-card[data-severity=serious]  { border-left-color: var(--se); }
.issue-card[data-severity=moderate] { border-left-color: var(--mo); }
.issue-card[data-severity=minor]    { border-left-color: var(--mi); }

.issue-card-header {
  display: flex; align-items: flex-start; gap: 12px;
  padding: 14px 16px; cursor: pointer; user-select: none;
  transition: background 0.1s;
}
.issue-card-header:hover { background: var(--bg2); }

.issue-left { display: flex; align-items: center; gap: 8px; flex-shrink: 0; }
.issue-num { font-size: 11px; font-weight: 600; color: var(--ink3); font-family: var(--mono); min-width: 20px; text-align: right; }
.sev-badge {
  font-size: 10px; font-weight: 600; padding: 2px 6px; border-radius: 2px; color: white;
  text-transform: uppercase; letter-spacing: 0.3px; flex-shrink: 0;
}
.sev-badge.sev-critical { background: var(--cr); }
.sev-badge.sev-serious  { background: var(--se); }
.sev-badge.sev-moderate { background: var(--mo); }
.sev-badge.sev-minor    { background: var(--mi); }
.check-tag { font-size: 10px; color: var(--ink3); font-family: var(--mono); flex-shrink: 0; }

.issue-center { flex: 1; min-width: 0; }
.issue-message { font-size: 13px; color: var(--ink); line-height: 1.4; }
.issue-path { font-size: 11px; color: var(--ink3); font-family: var(--mono); margin-top: 2px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }

.issue-right { display: flex; align-items: center; gap: 8px; flex-shrink: 0; }
.wcag-tag { font-size: 10px; color: var(--ink3); font-family: var(--mono); }
.toggle-icon { font-size: 16px; color: var(--ink3); transition: transform 0.2s; display: inline-block; }
.toggle-icon.open { transform: rotate(90deg); }

.issue-card-body { padding: 16px; border-top: 1px solid var(--border); background: var(--bg2); }

.detail-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
.detail-block h4 { font-size: 10px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: var(--ink3); margin-bottom: 6px; }
.detail-block p { font-size: 12px; color: var(--ink2); line-height: 1.5; }
.detail-block-wide { grid-column: span 2; }
.path-chain { font-family: var(--mono); font-size: 11px; color: var(--ink2); }

.detail-table { width: 100%; border-collapse: collapse; font-size: 12px; }
.detail-table tr:not(:last-child) td { border-bottom: 1px solid var(--border); }
.detail-key { padding: 5px 8px 5px 0; color: var(--ink3); width: 40%; }
.detail-val { padding: 5px 0; color: var(--ink); font-family: var(--mono); font-size: 11px; }

.fix-suggestion { font-size: 12px; color: var(--ink2); line-height: 1.5; padding: 8px 12px; background: #fffbeb; border-left: 2px solid #f59e0b; border-radius: 2px; }

.page-footer {
  text-align: center; padding: 24px; font-size: 11px; color: var(--ink3);
  border-top: 1px solid var(--border); max-width: 900px; margin: 0 auto;
}

@media (max-width: 600px) {
  .stat-grid { grid-template-columns: repeat(2, 1fr); }
  .detail-grid { grid-template-columns: 1fr; }
  .detail-block-wide { grid-column: span 1; }
  .issue-card-header { flex-wrap: wrap; }
  .page-main { padding: 16px; }
}
`;

// ─── Embedded JS ─────────────────────────────────────────────────────────────

const JS = `
function toggleCard(header) {
  const body = header.nextElementSibling;
  const icon = header.querySelector('.toggle-icon');
  const isOpen = body.style.display !== 'none';
  body.style.display = isOpen ? 'none' : 'block';
  icon.classList.toggle('open', !isOpen);
}

function filterIssues(btn) {
  const severity = btn.dataset.severity;
  document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
  btn.classList.add('active');
  document.querySelectorAll('.issue-card').forEach(card => {
    if (severity === 'all' || card.dataset.severity === severity) {
      card.style.display = '';
    } else {
      card.style.display = 'none';
    }
  });
}
`;
